export const TPR_GENERATE_FLAG = 'TPR_GENERATE_FLAG'
export const TPR_WARNING = `
/**
 * ===========================================
 *              ${TPR_GENERATE_FLAG}
 * ===========================================
 * !!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!
 * ===========================================
 * This file is generated by Taro-Pick-Runner.
 * DO NOT COMMIT this file to your project!!!!
 * FIXME git checkout -- [this file]
 */
`