/*
 * @Author: Curtis.Liong
 * @Date: 2021-05-24 17:33:38
 * @Last Modified by:   Curtis.Liong
 * @Last Modified time: 2021-05-24 17:33:38
 */
export const TPP_STORAGE_NAME = 'taro-page-picker.json'
export const TPP_GENERATE_FLAG = 'TPP_GENERATE_FLAG'
export const TPP_WARNING = `
/**
 * ===========================================
 *              ${TPP_GENERATE_FLAG}
 * ===========================================
 * !!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!
 * ===========================================
 * This file is generated by Taro-Page-Picker.
 * DO NOT COMMIT this file to your project!!!!
 * FIXME git checkout -- [this file]
 */
`
